name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vbukv-${{ github.ref_name }}-x86_64-linux
          path: target/release/vbukv-cli

      - name: Rename
        run: mv target/release/vbukv-cli target/release/vbukv-${{ github.ref_name }}-x86_64-linux

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          files: |
            target/release/vbukv-${{ github.ref_name }}-x86_64-linux
