name: Rust

on:
  push:
    #branches: [ "master" ]
  #pull_request:
    # branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test --verbose
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vbukv
        path: target/release/vbukv
