name: Development

on:
  push:
    #branches: [ "master" ]
  #pull_request:
    # branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  #unit:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
  #    - name: Test
  #      run: cargo test

  build:
    #needs: unit
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vbukv
        path: target/release/vbukv
    - name: Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        #draft: true
        prerelease: false
        #title: "Development Build"
        files: |
          target/release/vbukv
